// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtiNmbguBKDDJG4xtP8XY6WoabAdpQ5v4',
    appId: '1:17107545971:web:9773943922571bb4c71f06',
    messagingSenderId: '17107545971',
    projectId: 'flutterebookapp-4276f',
    authDomain: 'flutterebookapp-4276f.firebaseapp.com',
    storageBucket: 'flutterebookapp-4276f.appspot.com',
    measurementId: 'G-PT1YYV8995',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGwtnuMwjRjescTuAnfcumP1BKtrbHc4',
    appId: '1:17107545971:android:5173ee5192ec77e2c71f06',
    messagingSenderId: '17107545971',
    projectId: 'flutterebookapp-4276f',
    storageBucket: 'flutterebookapp-4276f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUmH6MdkIrcJhRwUBzGhKsn9huVTexW7c',
    appId: '1:17107545971:ios:ba95339119e82ccdc71f06',
    messagingSenderId: '17107545971',
    projectId: 'flutterebookapp-4276f',
    storageBucket: 'flutterebookapp-4276f.appspot.com',
    androidClientId: '17107545971-ko6al5sg9mf1r92pdrhoqf392d5qp2sf.apps.googleusercontent.com',
    iosClientId: '17107545971-t7kvi7k6ukkjrojpsqco4j490ffajbvp.apps.googleusercontent.com',
    iosBundleId: 'dev.jideguru.flutterEbookApp234',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUmH6MdkIrcJhRwUBzGhKsn9huVTexW7c',
    appId: '1:17107545971:ios:f85480b144fbced8c71f06',
    messagingSenderId: '17107545971',
    projectId: 'flutterebookapp-4276f',
    storageBucket: 'flutterebookapp-4276f.appspot.com',
    androidClientId: '17107545971-ko6al5sg9mf1r92pdrhoqf392d5qp2sf.apps.googleusercontent.com',
    iosClientId: '17107545971-9bqf6emnff7b1i6ho457cura91ap7hjj.apps.googleusercontent.com',
    iosBundleId: 'dev.jideguru.flutterEbookApp',
  );
}
